project:
  type: website
  output-dir: docs
  render: 
    - "*.qmd"
    - "!README.md"

website:
#  title: "Esteve Aqachmar"
  search: false
  favicon: logo1.png
  google-analytics: "G-6757JXF874"
  # cookie-consent: # U.S visitors only
  #   type: express
  #   style: simple
  navbar:
    background: "#002D73"
    left:
      - href: index.qmd
    right: 
      - href: blog.qmd
      - icon: linkedin
        href: https://www.linkedin.com/in/esteveaqachmar/
      - icon: twitter-x
        href: https://twitter.com/esteveaqa
      - icon: github
        href: https://github.com/esteveaq  
  page-footer:
    center:
      - text: "Home"
        href: https://esteveaq.github.io/
      - icon: linkedin
        href: https://www.linkedin.com/in/esteveaqachmar/
      - icon: twitter-x
        href: https://twitter.com/esteveaqa
      - icon: github
        href: https://github.com/esteveaq 
      - text: "2026"
    background: "#002D73"

format:
  html:
    theme: cosmo
    linkcolor: "#002D73"
    toc: false



